Fix build without svn: make sure SVNVERSION is always a single word
svnversion prints "Unversioned directory" if we are not in svn repository.
This causes problems when evaluating gcc command line options like:
-D_VER_SVN=$(SVNVERSION) => -D_VER_SVN=Unversioned directory
In this case gcc reports:
error: directory: No such file or directory



git-svn-id: http://192.168.42.160/software/main@27568 ce24552a-085e-4656-8849-d4bfd34db3c6